### ISSUE TITLE
Add a `fetch()` option for invoking this mode?

### ISSUE THREAD

**Issue by slightlyoff** [mikewest/credentiallessness#3]
It'd be great to have a way to issue requests that have this behavior, both via attribute on `<img>`, <script>`, and `<link>` as well as via flag to `fetch()`.

Thoughts?

**Comment by mikewest** [comment]
`fetch(url, { mode: "no-cors", credentials: "omit" })` does what you want for `fetch`, I think. We don't have a mechanism for specifying those kinds of options on `<img>`, `<script>`, etc. It doesn't seem at all unreasonable to me to add such a mechanism.

I think this request boils down to something similar to https://github.com/whatwg/html/issues/2614. It's pretty unrelated to the COEP mechanism, however, so perhaps we can move the conversation over there?

**Comment by ArthurSonzogni** [comment]
There are also:
X.crossOrigin=("anonymous" | "use-credentialess")`

For `<img>`, `<script>`, `<link>`, `<video>`, ...

This doesn't let you specify independently the `mode` (CORS|NO-CORS) and the `credentials mode` independently though, contrary to `fetch`.

Expected interactions with `COEP:credentialless`: tested here:
1. [img](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/external/wpt/html/cross-origin-embedder-policy/credentialless/image.tentative.https.html)
2. [script](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/external/wpt/html/cross-origin-embedder-policy/credentialless/script.tentative.https.html)
3. [link](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/external/wpt/html/cross-origin-embedder-policy/credentialless/link.tentative.https.html)
4. [video](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/external/wpt/html/cross-origin-embedder-policy/credentialless/video.tentative.https.window.js)

I think I can close this issue, since it belong outside of COEP:credentialless.
